"""add_ticktick_metadata_and_suggestions

Revision ID: 232f0f5bae6c
Revises: cc3e5f2c9b4c
Create Date: 2025-12-11 02:16:50.384947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '232f0f5bae6c'
down_revision: Union[str, None] = 'cc3e5f2c9b4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticktick_project_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_ticktick_project_id'), 'projects', ['ticktick_project_id'], unique=True)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('task_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('suggestion_type', sa.String(length=100), nullable=False),
    sa.Column('current_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('suggested_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='suggestionstatus'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_suggestions_id'), 'task_suggestions', ['id'], unique=False)
    op.create_index(op.f('ix_task_suggestions_status'), 'task_suggestions', ['status'], unique=False)
    op.create_index(op.f('ix_task_suggestions_task_id'), 'task_suggestions', ['task_id'], unique=False)
    op.drop_constraint('profiles_user_id_key', 'profiles', type_='unique')
    op.add_column('tasks', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('ticktick_priority', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('all_day', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('tasks', sa.Column('reminder_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('repeat_flag', sa.String(length=255), nullable=True))
    op.add_column('tasks', sa.Column('project_name', sa.String(length=500), nullable=True))
    op.add_column('tasks', sa.Column('parent_task_id', sa.String(length=255), nullable=True))
    op.add_column('tasks', sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('tasks', sa.Column('column_id', sa.String(length=255), nullable=True))
    op.add_column('tasks', sa.Column('ticktick_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tasks', sa.Column('time_estimate', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('focus_time', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('last_modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('tasks', sa.Column('sync_version', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tasks_project_id_fkey', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'sync_version')
    op.drop_column('tasks', 'last_modified_at')
    op.drop_column('tasks', 'last_synced_at')
    op.drop_column('tasks', 'focus_time')
    op.drop_column('tasks', 'time_estimate')
    op.drop_column('tasks', 'ticktick_tags')
    op.drop_column('tasks', 'column_id')
    op.drop_column('tasks', 'sort_order')
    op.drop_column('tasks', 'parent_task_id')
    op.drop_column('tasks', 'project_name')
    op.drop_column('tasks', 'repeat_flag')
    op.drop_column('tasks', 'reminder_time')
    op.drop_column('tasks', 'all_day')
    op.drop_column('tasks', 'start_date')
    op.drop_column('tasks', 'ticktick_priority')
    op.drop_column('tasks', 'project_id')
    op.create_unique_constraint('profiles_user_id_key', 'profiles', ['user_id'])
    op.drop_index(op.f('ix_task_suggestions_task_id'), table_name='task_suggestions')
    op.drop_index(op.f('ix_task_suggestions_status'), table_name='task_suggestions')
    op.drop_index(op.f('ix_task_suggestions_id'), table_name='task_suggestions')
    op.drop_table('task_suggestions')
    # Drop the enum type
    op.execute('DROP TYPE IF EXISTS suggestionstatus')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_ticktick_project_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
