"""add_is_sorted_field_to_tasks

Revision ID: 3de60c912377
Revises: 232f0f5bae6c
Create Date: 2025-12-11 02:46:08.451049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3de60c912377'
down_revision: Union[str, None] = '232f0f5bae6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add is_sorted column with default False
    op.add_column('tasks', sa.Column('is_sorted', sa.Boolean(), nullable=False, server_default=sa.false()))

    # Backfill existing data: Set is_sorted = True for tasks with a quadrant
    op.execute(
        "UPDATE tasks SET is_sorted = TRUE WHERE eisenhower_quadrant IS NOT NULL"
    )

    # Remove server default after backfill (defaults handled by SQLAlchemy)
    op.alter_column('tasks', 'is_sorted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)

    op.alter_column('tasks', 'all_day',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tasks', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tasks', 'sync_version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_tasks_is_sorted'), 'tasks', ['is_sorted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_is_sorted'), table_name='tasks')
    op.alter_column('tasks', 'sync_version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('tasks', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('tasks', 'all_day',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_column('tasks', 'is_sorted')
    # ### end Alembic commands ###
