"""Add LLM configurations and update settings schema

Revision ID: b13720d6c407
Revises: c80af71a8fdf
Create Date: 2025-12-12 17:18:35.253107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b13720d6c407'
down_revision: Union[str, None] = 'c80af71a8fdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create the llm_configurations table using the existing enum type
    op.create_table('llm_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('provider', postgresql.ENUM('OLLAMA', 'OPENROUTER', 'ANTHROPIC', 'OPENAI', 'GEMINI', name='llmprovider', create_type=False), nullable=False),
    sa.Column('model', sa.String(length=500), nullable=False),
    sa.Column('api_key', sa.String(length=500), nullable=True),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connection_status', sa.String(length=20), nullable=False),
    sa.Column('connection_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_configurations_id'), 'llm_configurations', ['id'], unique=False)
    op.create_index(op.f('ix_llm_configurations_user_id'), 'llm_configurations', ['user_id'], unique=False)
    op.add_column('settings', sa.Column('active_llm_config_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_settings_active_llm_config_id'), 'settings', ['active_llm_config_id'], unique=False)
    op.create_foreign_key(None, 'settings', 'llm_configurations', ['active_llm_config_id'], ['id'], ondelete='SET NULL')
    op.drop_column('settings', 'llm_model')
    op.drop_column('settings', 'llm_provider')
    op.drop_column('settings', 'llm_api_key')
    op.drop_column('settings', 'llm_max_tokens')
    op.drop_column('settings', 'llm_temperature')
    op.drop_column('settings', 'llm_base_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('llm_base_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('llm_temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('llm_max_tokens', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('llm_api_key', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('llm_provider', postgresql.ENUM('OLLAMA', 'GEMINI', 'OPENROUTER', 'ANTHROPIC', name='llmprovider'), autoincrement=False, nullable=False))
    op.add_column('settings', sa.Column('llm_model', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'settings', type_='foreignkey')
    op.drop_index(op.f('ix_settings_active_llm_config_id'), table_name='settings')
    op.drop_column('settings', 'active_llm_config_id')
    op.drop_index(op.f('ix_llm_configurations_user_id'), table_name='llm_configurations')
    op.drop_index(op.f('ix_llm_configurations_id'), table_name='llm_configurations')
    op.drop_table('llm_configurations')
    # ### end Alembic commands ###
