"""Add user memory store and profile preference fields

Revision ID: d4f8e9a1b2c3
Revises: 0faa2669a272
Create Date: 2025-12-23 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4f8e9a1b2c3'
down_revision: Union[str, None] = '0faa2669a272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create user_memories table
    op.create_table('user_memories',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('namespace', sa.String(length=100), nullable=False),
        sa.Column('key', sa.String(length=255), nullable=False),
        sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_memories_id'), 'user_memories', ['id'], unique=False)
    op.create_index(op.f('ix_user_memories_user_id'), 'user_memories', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_memories_namespace'), 'user_memories', ['namespace'], unique=False)
    op.create_index('ix_user_namespace_key', 'user_memories', ['user_id', 'namespace', 'key'], unique=True)

    # Add profile preference fields
    op.add_column('profiles', sa.Column('work_style', sa.String(length=50), nullable=True,
                  comment='deep_focus, meeting_heavy, context_switcher, structured, flexible'))
    op.add_column('profiles', sa.Column('preferred_tone', sa.String(length=50), nullable=True,
                  comment='professional, friendly, casual, direct, encouraging'))
    op.add_column('profiles', sa.Column('energy_pattern', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('profiles', sa.Column('communication_style', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove profile preference fields
    op.drop_column('profiles', 'communication_style')
    op.drop_column('profiles', 'energy_pattern')
    op.drop_column('profiles', 'preferred_tone')
    op.drop_column('profiles', 'work_style')

    # Drop user_memories table
    op.drop_index('ix_user_namespace_key', table_name='user_memories')
    op.drop_index(op.f('ix_user_memories_namespace'), table_name='user_memories')
    op.drop_index(op.f('ix_user_memories_user_id'), table_name='user_memories')
    op.drop_index(op.f('ix_user_memories_id'), table_name='user_memories')
    op.drop_table('user_memories')

    # ### end Alembic commands ###
