"""Add dynamic LLM configuration to settings

Revision ID: e839eebff7b4
Revises: 3de60c912377
Create Date: 2025-12-12 15:53:40.114739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e839eebff7b4'
down_revision: Union[str, None] = '3de60c912377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('llm_model', sa.String(length=500), nullable=True))
    op.add_column('settings', sa.Column('llm_api_key', sa.String(length=500), nullable=True))
    op.add_column('settings', sa.Column('llm_base_url', sa.String(length=500), nullable=True))
    op.add_column('settings', sa.Column('llm_temperature', sa.Float(), nullable=True))
    op.add_column('settings', sa.Column('llm_max_tokens', sa.Integer(), nullable=True))
    op.drop_column('settings', 'ollama_url')
    op.drop_column('settings', 'openrouter_model')
    op.drop_column('settings', 'ollama_model')
    op.drop_column('settings', 'gemini_api_key')
    op.drop_column('settings', 'openrouter_api_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('openrouter_api_key', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('gemini_api_key', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('ollama_model', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('openrouter_model', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('ollama_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('settings', 'llm_max_tokens')
    op.drop_column('settings', 'llm_temperature')
    op.drop_column('settings', 'llm_base_url')
    op.drop_column('settings', 'llm_api_key')
    op.drop_column('settings', 'llm_model')
    # ### end Alembic commands ###
